/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerNameRouteImport } from './routes/$serverName'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCallbackRouteImport } from './routes/admin/callback'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsProviderRouteImport } from './routes/docs/$provider'
import { Route as AdminServerNameEditRouteImport } from './routes/admin/$serverName.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerNameRoute = ServerNameRouteImport.update({
  id: '/$serverName',
  path: '/$serverName',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbackRoute = AdminCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProviderRoute = DocsProviderRouteImport.update({
  id: '/docs/$provider',
  path: '/docs/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServerNameEditRoute = AdminServerNameEditRouteImport.update({
  id: '/$serverName/edit',
  path: '/$serverName/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serverName': typeof ServerNameRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/new': typeof AdminNewRoute
  '/docs/$provider': typeof DocsProviderRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/$serverName/edit': typeof AdminServerNameEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serverName': typeof ServerNameRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/new': typeof AdminNewRoute
  '/docs/$provider': typeof DocsProviderRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/$serverName/edit': typeof AdminServerNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serverName': typeof ServerNameRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/new': typeof AdminNewRoute
  '/docs/$provider': typeof DocsProviderRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/$serverName/edit': typeof AdminServerNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serverName'
    | '/admin'
    | '/admin/callback'
    | '/admin/new'
    | '/docs/$provider'
    | '/admin/'
    | '/docs/'
    | '/admin/$serverName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$serverName'
    | '/admin/callback'
    | '/admin/new'
    | '/docs/$provider'
    | '/admin'
    | '/docs'
    | '/admin/$serverName/edit'
  id:
    | '__root__'
    | '/'
    | '/$serverName'
    | '/admin'
    | '/admin/callback'
    | '/admin/new'
    | '/docs/$provider'
    | '/admin/'
    | '/docs/'
    | '/admin/$serverName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServerNameRoute: typeof ServerNameRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsProviderRoute: typeof DocsProviderRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serverName': {
      id: '/$serverName'
      path: '/$serverName'
      fullPath: '/$serverName'
      preLoaderRoute: typeof ServerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callback': {
      id: '/admin/callback'
      path: '/callback'
      fullPath: '/admin/callback'
      preLoaderRoute: typeof AdminCallbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$provider': {
      id: '/docs/$provider'
      path: '/docs/$provider'
      fullPath: '/docs/$provider'
      preLoaderRoute: typeof DocsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$serverName/edit': {
      id: '/admin/$serverName/edit'
      path: '/$serverName/edit'
      fullPath: '/admin/$serverName/edit'
      preLoaderRoute: typeof AdminServerNameEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCallbackRoute: typeof AdminCallbackRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminServerNameEditRoute: typeof AdminServerNameEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCallbackRoute: AdminCallbackRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminServerNameEditRoute: AdminServerNameEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServerNameRoute: ServerNameRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsProviderRoute: DocsProviderRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
