/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerNameRouteImport } from './routes/$serverName'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountCallbackRouteImport } from './routes/account/callback'
import { Route as AccountModelsRouteImport } from './routes/account/models'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCallbackRouteImport } from './routes/admin/callback'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsProviderRouteImport } from './routes/docs/$provider'
import { Route as AdminServerNameEditRouteImport } from './routes/admin/$serverName.edit'
import { Route as AdminAuthProvidersIndexRouteImport } from './routes/admin/auth-providers/index'
import { Route as AdminAuthProvidersNewRouteImport } from './routes/admin/auth-providers/new'
import { Route as AdminModelsIndexRouteImport } from './routes/admin/models/index'
import { Route as AdminModelsNewRouteImport } from './routes/admin/models/new'
import { Route as AdminAuthProvidersProviderNameEditRouteImport } from './routes/admin/auth-providers/$providerName.edit'
import { Route as AdminModelsModelNameEditRouteImport } from './routes/admin/models/$modelName.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerNameRoute = ServerNameRouteImport.update({
  id: '/$serverName',
  path: '/$serverName',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCallbackRoute = AccountCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AccountRoute,
} as any)
const AccountModelsRoute = AccountModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbackRoute = AdminCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProviderRoute = DocsProviderRouteImport.update({
  id: '/docs/$provider',
  path: '/docs/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServerNameEditRoute = AdminServerNameEditRouteImport.update({
  id: '/$serverName/edit',
  path: '/$serverName/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthProvidersIndexRoute = AdminAuthProvidersIndexRouteImport.update({
  id: '/auth-providers/',
  path: '/auth-providers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthProvidersNewRoute = AdminAuthProvidersNewRouteImport.update({
  id: '/auth-providers/new',
  path: '/auth-providers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsIndexRoute = AdminModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsNewRoute = AdminModelsNewRouteImport.update({
  id: '/models/new',
  path: '/models/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthProvidersProviderNameEditRoute =
  AdminAuthProvidersProviderNameEditRouteImport.update({
    id: '/auth-providers/$providerName/edit',
    path: '/auth-providers/$providerName/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminModelsModelNameEditRoute =
  AdminModelsModelNameEditRouteImport.update({
    id: '/models/$modelName/edit',
    path: '/models/$modelName/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serverName': typeof ServerNameRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/account/callback': typeof AccountCallbackRoute
  '/account/models': typeof AccountModelsRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/new': typeof AdminNewRoute
  '/docs/$provider': typeof DocsProviderRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/$serverName/edit': typeof AdminServerNameEditRoute
  '/admin/auth-providers/new': typeof AdminAuthProvidersNewRoute
  '/admin/models/new': typeof AdminModelsNewRoute
  '/admin/auth-providers/': typeof AdminAuthProvidersIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
  '/admin/auth-providers/$providerName/edit': typeof AdminAuthProvidersProviderNameEditRoute
  '/admin/models/$modelName/edit': typeof AdminModelsModelNameEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serverName': typeof ServerNameRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/models': typeof AccountModelsRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/new': typeof AdminNewRoute
  '/docs/$provider': typeof DocsProviderRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/$serverName/edit': typeof AdminServerNameEditRoute
  '/admin/auth-providers/new': typeof AdminAuthProvidersNewRoute
  '/admin/models/new': typeof AdminModelsNewRoute
  '/admin/auth-providers': typeof AdminAuthProvidersIndexRoute
  '/admin/models': typeof AdminModelsIndexRoute
  '/admin/auth-providers/$providerName/edit': typeof AdminAuthProvidersProviderNameEditRoute
  '/admin/models/$modelName/edit': typeof AdminModelsModelNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serverName': typeof ServerNameRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/account/callback': typeof AccountCallbackRoute
  '/account/models': typeof AccountModelsRoute
  '/admin/callback': typeof AdminCallbackRoute
  '/admin/new': typeof AdminNewRoute
  '/docs/$provider': typeof DocsProviderRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/$serverName/edit': typeof AdminServerNameEditRoute
  '/admin/auth-providers/new': typeof AdminAuthProvidersNewRoute
  '/admin/models/new': typeof AdminModelsNewRoute
  '/admin/auth-providers/': typeof AdminAuthProvidersIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
  '/admin/auth-providers/$providerName/edit': typeof AdminAuthProvidersProviderNameEditRoute
  '/admin/models/$modelName/edit': typeof AdminModelsModelNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serverName'
    | '/account'
    | '/admin'
    | '/account/callback'
    | '/account/models'
    | '/admin/callback'
    | '/admin/new'
    | '/docs/$provider'
    | '/account/'
    | '/admin/'
    | '/docs/'
    | '/admin/$serverName/edit'
    | '/admin/auth-providers/new'
    | '/admin/models/new'
    | '/admin/auth-providers/'
    | '/admin/models/'
    | '/admin/auth-providers/$providerName/edit'
    | '/admin/models/$modelName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$serverName'
    | '/account/callback'
    | '/account/models'
    | '/admin/callback'
    | '/admin/new'
    | '/docs/$provider'
    | '/account'
    | '/admin'
    | '/docs'
    | '/admin/$serverName/edit'
    | '/admin/auth-providers/new'
    | '/admin/models/new'
    | '/admin/auth-providers'
    | '/admin/models'
    | '/admin/auth-providers/$providerName/edit'
    | '/admin/models/$modelName/edit'
  id:
    | '__root__'
    | '/'
    | '/$serverName'
    | '/account'
    | '/admin'
    | '/account/callback'
    | '/account/models'
    | '/admin/callback'
    | '/admin/new'
    | '/docs/$provider'
    | '/account/'
    | '/admin/'
    | '/docs/'
    | '/admin/$serverName/edit'
    | '/admin/auth-providers/new'
    | '/admin/models/new'
    | '/admin/auth-providers/'
    | '/admin/models/'
    | '/admin/auth-providers/$providerName/edit'
    | '/admin/models/$modelName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServerNameRoute: typeof ServerNameRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DocsProviderRoute: typeof DocsProviderRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serverName': {
      id: '/$serverName'
      path: '/$serverName'
      fullPath: '/$serverName'
      preLoaderRoute: typeof ServerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/callback': {
      id: '/account/callback'
      path: '/callback'
      fullPath: '/account/callback'
      preLoaderRoute: typeof AccountCallbackRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/models': {
      id: '/account/models'
      path: '/models'
      fullPath: '/account/models'
      preLoaderRoute: typeof AccountModelsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callback': {
      id: '/admin/callback'
      path: '/callback'
      fullPath: '/admin/callback'
      preLoaderRoute: typeof AdminCallbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$provider': {
      id: '/docs/$provider'
      path: '/docs/$provider'
      fullPath: '/docs/$provider'
      preLoaderRoute: typeof DocsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$serverName/edit': {
      id: '/admin/$serverName/edit'
      path: '/$serverName/edit'
      fullPath: '/admin/$serverName/edit'
      preLoaderRoute: typeof AdminServerNameEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth-providers/': {
      id: '/admin/auth-providers/'
      path: '/auth-providers'
      fullPath: '/admin/auth-providers/'
      preLoaderRoute: typeof AdminAuthProvidersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth-providers/new': {
      id: '/admin/auth-providers/new'
      path: '/auth-providers/new'
      fullPath: '/admin/auth-providers/new'
      preLoaderRoute: typeof AdminAuthProvidersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models/': {
      id: '/admin/models/'
      path: '/models'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AdminModelsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models/new': {
      id: '/admin/models/new'
      path: '/models/new'
      fullPath: '/admin/models/new'
      preLoaderRoute: typeof AdminModelsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auth-providers/$providerName/edit': {
      id: '/admin/auth-providers/$providerName/edit'
      path: '/auth-providers/$providerName/edit'
      fullPath: '/admin/auth-providers/$providerName/edit'
      preLoaderRoute: typeof AdminAuthProvidersProviderNameEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models/$modelName/edit': {
      id: '/admin/models/$modelName/edit'
      path: '/models/$modelName/edit'
      fullPath: '/admin/models/$modelName/edit'
      preLoaderRoute: typeof AdminModelsModelNameEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountCallbackRoute: typeof AccountCallbackRoute
  AccountModelsRoute: typeof AccountModelsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountCallbackRoute: AccountCallbackRoute,
  AccountModelsRoute: AccountModelsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminCallbackRoute: typeof AdminCallbackRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminServerNameEditRoute: typeof AdminServerNameEditRoute
  AdminAuthProvidersNewRoute: typeof AdminAuthProvidersNewRoute
  AdminModelsNewRoute: typeof AdminModelsNewRoute
  AdminAuthProvidersIndexRoute: typeof AdminAuthProvidersIndexRoute
  AdminModelsIndexRoute: typeof AdminModelsIndexRoute
  AdminAuthProvidersProviderNameEditRoute: typeof AdminAuthProvidersProviderNameEditRoute
  AdminModelsModelNameEditRoute: typeof AdminModelsModelNameEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCallbackRoute: AdminCallbackRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminServerNameEditRoute: AdminServerNameEditRoute,
  AdminAuthProvidersNewRoute: AdminAuthProvidersNewRoute,
  AdminModelsNewRoute: AdminModelsNewRoute,
  AdminAuthProvidersIndexRoute: AdminAuthProvidersIndexRoute,
  AdminModelsIndexRoute: AdminModelsIndexRoute,
  AdminAuthProvidersProviderNameEditRoute:
    AdminAuthProvidersProviderNameEditRoute,
  AdminModelsModelNameEditRoute: AdminModelsModelNameEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServerNameRoute: ServerNameRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DocsProviderRoute: DocsProviderRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
