

[default]
[private]
_:
    @just --list --list-submodules

install:
    npm install

upgrade:
    npm update

gen:
    uv run proxy openapi ../openapi.json
    npm exec -- orval

lint:
    npm exec -- biome check --write
    just --unstable --fmt

dev:
    npm run dev
