import { defineConfig } from "orval";

export default defineConfig({
	gateway: {
		input: "../openapi.json",
		output: {
			target: "./src/api/generated",
			client: "fetch",
			prettier: true,
			clean: true,
			override: {
				mutator: {
					path: "./src/lib/api-fetch.ts",
					name: "apiFetch",
					extension: ".ts",
				},
				header: () =>
					[
						"/* eslint-disable */",
						"/*",
						" * Generated by orval — do not edit manually.",
						" * Regenerate with `just gen` from the ui directory.",
						" */",
						"",
					].join("\n"),
			},
		},
	},
});
